[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    fastled/FastLED @ ^3.7.0
    schreibfaul1/ESP32-audioI2S @ ^2.0.0
    tzapu/WiFiManager @ ^2.0.17

board_build.filesystem = littlefs
